[package]
name = "pr_demon"
version = "0.1.0"
authors = ["Yong Wen Chua <me@yongwen.xyz>"]

[[bin]]
name = "pr_demon"
test = true

[dependencies]
chrono = "0.3"
cron = "0.0.2"
docopt = "0.7.0"
fern = "0.3"
futures = "0.1.7"
hyper = "0.10"
log = "0.3"
rustc-serialize = "0.3"
telebot = "0.1.1"
time = "0.1"
tokio-core = "0.1.2"
url = "1.0"

[dev-dependencies]
timebomb = "0.1"
