[package]
name = "pr_demon"
version = "0.1.0"
authors = ["Yong Wen Chua <me@yongwen.xyz>"]

[[bin]]
name = "pr_demon"
test = true

[dependencies]
hyper = "*"
rustc-serialize = "*"
telegram-bot = "0.4"
time = "*"
url = "*"
cron = "0.0.2"
chrono = "*"

[dev-dependencies]
timebomb = "*"
