[package]
name = "pr_demon"
version = "0.1.0"
authors = ["Yong Wen Chua <me@yongwen.xyz>"]

[[bin]]
name = "pr_demon"
test = true

[dependencies]
chrono = "0.3"
cron = "0.0.2"
docopt = "0.7.0"
fern = "0.3"
fusionner = { git = "https://github.com/lawliet89/fusionner", rev = "b26e3fed1404b4d5e3badf8ec2292442ed5302a5" }
git2 = { git = "https://github.com/alexcrichton/git2-rs.git", rev = "0d745cf0efad95a9e407beecd7b508ca9a37df80" }
hyper = "0.10"
log = "0.3"
reqwest = "0.4"
rustc-serialize = "0.3"
time = "0.1"
url = "1.0"

[dev-dependencies]
timebomb = "0.1"
